name: Deploy Notion to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    
    - name: Clone loconotion repository
      run: |
        git clone https://github.com/leoncvlt/loconotion.git

    - name: Install loconotion dependencies
      run: |
        cd loconotion
        pip install -r requirements.txt

    - name: Export Notion page to HTML
      env:
        NOTION_PAGE_URL: ${{ secrets.NOTION_PAGE_URL }}
      run: |
        cd loconotion
        python loconotion $NOTION_PAGE_URL --clean
    
    - name: List files in dist/sarmad-ai
      run: ls loconotion/dist/sarmad-ai
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: github-pages
        path: loconotion/dist/sarmad-ai

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifact_name: github-pages
