name: Deploy Notion to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    
    - name: Clone loconotion repository
      run: |
        git clone https://github.com/leoncvlt/loconotion.git

    - name: Install loconotion dependencies
      run: |
        cd loconotion
        pip install -r requirements.txt

    - name: Export Notion page to HTML
      env:
        NOTION_PAGE_URL: ${{ secrets.NOTION_PAGE_URL }}
        OUTPUT_DIR: 'public'
      run: |
        cd loconotion
        python loconotion export $NOTION_PAGE_URL $OUTPUT_DIR

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target_branch: gh-pages
        build_dir: public
